module.exports = {
  ITEMS_PER_PAGE: 6,

  // Handle code for manga service
  MANGA_IS_FREE: 1,
  MANGA_NOT_FREE: 0,
  FILTER_BY_MANGA_UPDATE_DATE_DESC: 5000,
  FILTER_BY_MANGA_UPDATE_DATE_ASC: 5001,
  FILTER_BY_MANGA_NAME_ASC: 5002,
  FILTER_BY_MANGA_NAME_DESC: 5003,
  FILTER_BY_MANGA_VIEW_ASC: 5004,
  FILTER_BY_MANGA_VIEW_DESC: 5005,
  FILTER_BY_MANGA_LIKE_ASC: 5006,
  FILTER_BY_MANGA_LIKE_DESC: 5007,
  FILTER_BY_MANGA_CREATE_DATE_DESC: 5008,
  FILTER_BY_MANGA_CREATE_DATE_ASC: 5009,
};
